using NUnit.Framework;

using static Yoga.Net.YogaBuild;

namespace Yoga.Net.Tests.Typed
{
    [TestFixture]
    public class YogaPercentageTest
    {
        // @Generated by gentest/gentest.rb from gentest/fixtures/YogaPercentageTest.html
        [Test]
        public void percentage_width_height()
        {
            YogaConfig config = new YogaConfig();

            YogaNode root_child0;
            YogaNode root = Node(config, flexDirection: FlexDirection.Row, width: 200, height: 200)
               .Add(root_child0 = Node(config, width: 30.Percent(), height: 30.Percent()));

            YogaArrange.CalculateLayout(root, YogaValue.YGUndefined, YogaValue.YGUndefined, Direction.LTR);

            Assert.AreEqual(0, root.Layout.Left);
            Assert.AreEqual(0, root.Layout.Top);
            Assert.AreEqual(200, root.Layout.Width);
            Assert.AreEqual(200, root.Layout.Height);

            Assert.AreEqual(0, root_child0.Layout.Left);
            Assert.AreEqual(0, root_child0.Layout.Top);
            Assert.AreEqual(60, root_child0.Layout.Width);
            Assert.AreEqual(60, root_child0.Layout.Height);

            YogaArrange.CalculateLayout(root, YogaValue.YGUndefined, YogaValue.YGUndefined, Direction.RTL);

            Assert.AreEqual(0, root.Layout.Left);
            Assert.AreEqual(0, root.Layout.Top);
            Assert.AreEqual(200, root.Layout.Width);
            Assert.AreEqual(200, root.Layout.Height);

            Assert.AreEqual(140, root_child0.Layout.Left);
            Assert.AreEqual(0, root_child0.Layout.Top);
            Assert.AreEqual(60, root_child0.Layout.Width);
            Assert.AreEqual(60, root_child0.Layout.Height);
        }

        [Test]
        public void percentage_position_left_top()
        {
            YogaConfig config = new YogaConfig();

            YogaNode root_child0;
            YogaNode root = Node(config, flexDirection: FlexDirection.Row, width: 400, height: 400)
               .Add(root_child0 = Node(left: 10.Percent(), top: 20.Percent(), width: 45.Percent(), height: 55.Percent()));

            YogaArrange.CalculateLayout(root, YogaValue.YGUndefined, YogaValue.YGUndefined, Direction.LTR);

            Assert.AreEqual(0, root.Layout.Left);
            Assert.AreEqual(0, root.Layout.Top);
            Assert.AreEqual(400, root.Layout.Width);
            Assert.AreEqual(400, root.Layout.Height);

            Assert.AreEqual(40, root_child0.Layout.Left);
            Assert.AreEqual(80, root_child0.Layout.Top);
            Assert.AreEqual(180, root_child0.Layout.Width);
            Assert.AreEqual(220, root_child0.Layout.Height);

            YogaArrange.CalculateLayout(root, YogaValue.YGUndefined, YogaValue.YGUndefined, Direction.RTL);

            Assert.AreEqual(0, root.Layout.Left);
            Assert.AreEqual(0, root.Layout.Top);
            Assert.AreEqual(400, root.Layout.Width);
            Assert.AreEqual(400, root.Layout.Height);

            Assert.AreEqual(260, root_child0.Layout.Left);
            Assert.AreEqual(80, root_child0.Layout.Top);
            Assert.AreEqual(180, root_child0.Layout.Width);
            Assert.AreEqual(220, root_child0.Layout.Height);
        }

        [Test]
        public void percentage_position_bottom_right()
        {
            YogaConfig config = new YogaConfig();

            YogaNode root_child0;
            YogaNode root = Node(config, flexDirection: FlexDirection.Row, width: 500, height: 500)
               .Add(root_child0 = Node(right: 20.Percent(), bottom: 10.Percent(), width: 55.Percent(), height: 15.Percent()));

            YogaArrange.CalculateLayout(root, YogaValue.YGUndefined, YogaValue.YGUndefined, Direction.LTR);

            Assert.AreEqual(0, root.Layout.Left);
            Assert.AreEqual(0, root.Layout.Top);
            Assert.AreEqual(500, root.Layout.Width);
            Assert.AreEqual(500, root.Layout.Height);

            Assert.AreEqual(-100, root_child0.Layout.Left);
            Assert.AreEqual(-50, root_child0.Layout.Top);
            Assert.AreEqual(275, root_child0.Layout.Width);
            Assert.AreEqual(75, root_child0.Layout.Height);

            YogaArrange.CalculateLayout(root, YogaValue.YGUndefined, YogaValue.YGUndefined, Direction.RTL);

            Assert.AreEqual(0, root.Layout.Left);
            Assert.AreEqual(0, root.Layout.Top);
            Assert.AreEqual(500, root.Layout.Width);
            Assert.AreEqual(500, root.Layout.Height);

            Assert.AreEqual(125, root_child0.Layout.Left);
            Assert.AreEqual(-50, root_child0.Layout.Top);
            Assert.AreEqual(275, root_child0.Layout.Width);
            Assert.AreEqual(75, root_child0.Layout.Height);
        }

        [Test]
        public void percentage_flex_basis()
        {
            YogaConfig config = new YogaConfig();

            YogaNode root_child0, root_child1;
            YogaNode root = Node(config, flexDirection: FlexDirection.Row, width: 200, height: 200)
                           .Add(root_child0 = Node(flexGrow: 1, flexBasis: 50.Percent()))
                           .Add(root_child1 = Node(flexGrow: 1, flexBasis: 25.Percent()));

            YogaArrange.CalculateLayout(root, YogaValue.YGUndefined, YogaValue.YGUndefined, Direction.LTR);

            Assert.AreEqual(0, root.Layout.Left);
            Assert.AreEqual(0, root.Layout.Top);
            Assert.AreEqual(200, root.Layout.Width);
            Assert.AreEqual(200, root.Layout.Height);

            Assert.AreEqual(0, root_child0.Layout.Left);
            Assert.AreEqual(0, root_child0.Layout.Top);
            Assert.AreEqual(125, root_child0.Layout.Width);
            Assert.AreEqual(200, root_child0.Layout.Height);

            Assert.AreEqual(125, root_child1.Layout.Left);
            Assert.AreEqual(0, root_child1.Layout.Top);
            Assert.AreEqual(75, root_child1.Layout.Width);
            Assert.AreEqual(200, root_child1.Layout.Height);

            YogaArrange.CalculateLayout(root, YogaValue.YGUndefined, YogaValue.YGUndefined, Direction.RTL);

            Assert.AreEqual(0, root.Layout.Left);
            Assert.AreEqual(0, root.Layout.Top);
            Assert.AreEqual(200, root.Layout.Width);
            Assert.AreEqual(200, root.Layout.Height);

            Assert.AreEqual(75, root_child0.Layout.Left);
            Assert.AreEqual(0, root_child0.Layout.Top);
            Assert.AreEqual(125, root_child0.Layout.Width);
            Assert.AreEqual(200, root_child0.Layout.Height);

            Assert.AreEqual(0, root_child1.Layout.Left);
            Assert.AreEqual(0, root_child1.Layout.Top);
            Assert.AreEqual(75, root_child1.Layout.Width);
            Assert.AreEqual(200, root_child1.Layout.Height);
        }

        [Test]
        public void percentage_flex_basis_cross()
        {
            YogaConfig config = new YogaConfig();

            YogaNode root_child0, root_child1;
            YogaNode root = Node(width: 200, height: 200)
                           .Add(root_child0 = Node(flexGrow: 1, flexBasis: 50.Percent()))
                           .Add(root_child1 = Node(flexGrow: 1, flexBasis: 25.Percent()));

            YogaArrange.CalculateLayout(root, YogaValue.YGUndefined, YogaValue.YGUndefined, Direction.LTR);

            Assert.AreEqual(0, root.Layout.Left);
            Assert.AreEqual(0, root.Layout.Top);
            Assert.AreEqual(200, root.Layout.Width);
            Assert.AreEqual(200, root.Layout.Height);

            Assert.AreEqual(0, root_child0.Layout.Left);
            Assert.AreEqual(0, root_child0.Layout.Top);
            Assert.AreEqual(200, root_child0.Layout.Width);
            Assert.AreEqual(125, root_child0.Layout.Height);

            Assert.AreEqual(0, root_child1.Layout.Left);
            Assert.AreEqual(125, root_child1.Layout.Top);
            Assert.AreEqual(200, root_child1.Layout.Width);
            Assert.AreEqual(75, root_child1.Layout.Height);

            YogaArrange.CalculateLayout(root, YogaValue.YGUndefined, YogaValue.YGUndefined, Direction.RTL);

            Assert.AreEqual(0, root.Layout.Left);
            Assert.AreEqual(0, root.Layout.Top);
            Assert.AreEqual(200, root.Layout.Width);
            Assert.AreEqual(200, root.Layout.Height);

            Assert.AreEqual(0, root_child0.Layout.Left);
            Assert.AreEqual(0, root_child0.Layout.Top);
            Assert.AreEqual(200, root_child0.Layout.Width);
            Assert.AreEqual(125, root_child0.Layout.Height);

            Assert.AreEqual(0, root_child1.Layout.Left);
            Assert.AreEqual(125, root_child1.Layout.Top);
            Assert.AreEqual(200, root_child1.Layout.Width);
            Assert.AreEqual(75, root_child1.Layout.Height);
        }

        [Test]
        public void percentage_flex_basis_cross_min_height()
        {
            YogaConfig config = new YogaConfig();

            YogaNode root_child0, root_child1;
            YogaNode root = Node(width: 200, height: 200)
                           .Add(root_child0 = Node(flexGrow: 1, minHeight:60.Percent()))
                           .Add(root_child1 = Node(flexGrow: 2, minHeight:10.Percent()));

            YogaArrange.CalculateLayout(root, YogaValue.YGUndefined, YogaValue.YGUndefined, Direction.LTR);

            Assert.AreEqual(0, root.Layout.Left);
            Assert.AreEqual(0, root.Layout.Top);
            Assert.AreEqual(200, root.Layout.Width);
            Assert.AreEqual(200, root.Layout.Height);

            Assert.AreEqual(0, root_child0.Layout.Left);
            Assert.AreEqual(0, root_child0.Layout.Top);
            Assert.AreEqual(200, root_child0.Layout.Width);
            Assert.AreEqual(140, root_child0.Layout.Height);

            Assert.AreEqual(0, root_child1.Layout.Left);
            Assert.AreEqual(140, root_child1.Layout.Top);
            Assert.AreEqual(200, root_child1.Layout.Width);
            Assert.AreEqual(60, root_child1.Layout.Height);

            YogaArrange.CalculateLayout(root, YogaValue.YGUndefined, YogaValue.YGUndefined, Direction.RTL);

            Assert.AreEqual(0, root.Layout.Left);
            Assert.AreEqual(0, root.Layout.Top);
            Assert.AreEqual(200, root.Layout.Width);
            Assert.AreEqual(200, root.Layout.Height);

            Assert.AreEqual(0, root_child0.Layout.Left);
            Assert.AreEqual(0, root_child0.Layout.Top);
            Assert.AreEqual(200, root_child0.Layout.Width);
            Assert.AreEqual(140, root_child0.Layout.Height);

            Assert.AreEqual(0, root_child1.Layout.Left);
            Assert.AreEqual(140, root_child1.Layout.Top);
            Assert.AreEqual(200, root_child1.Layout.Width);
            Assert.AreEqual(60, root_child1.Layout.Height);
        }

        [Test]
        public void percentage_flex_basis_main_max_height()
        {
            YogaConfig config = new YogaConfig();

            YogaNode root_child0, root_child1;
            YogaNode root = Node(flexDirection:FlexDirection.Row, width: 200, height: 200)
                           .Add(root_child0 = Node(flexGrow: 1, flexBasis: 10.Percent(), maxHeight:60.Percent()))
                           .Add(root_child1 = Node(flexGrow: 4, flexBasis: 10.Percent(), maxHeight:20.Percent()));

            YogaArrange.CalculateLayout(root, YogaValue.YGUndefined, YogaValue.YGUndefined, Direction.LTR);

            Assert.AreEqual(0, root.Layout.Left);
            Assert.AreEqual(0, root.Layout.Top);
            Assert.AreEqual(200, root.Layout.Width);
            Assert.AreEqual(200, root.Layout.Height);

            Assert.AreEqual(0, root_child0.Layout.Left);
            Assert.AreEqual(0, root_child0.Layout.Top);
            Assert.AreEqual(52, root_child0.Layout.Width);
            Assert.AreEqual(120, root_child0.Layout.Height);

            Assert.AreEqual(52, root_child1.Layout.Left);
            Assert.AreEqual(0, root_child1.Layout.Top);
            Assert.AreEqual(148, root_child1.Layout.Width);
            Assert.AreEqual(40, root_child1.Layout.Height);

            YogaArrange.CalculateLayout(root, YogaValue.YGUndefined, YogaValue.YGUndefined, Direction.RTL);

            Assert.AreEqual(0, root.Layout.Left);
            Assert.AreEqual(0, root.Layout.Top);
            Assert.AreEqual(200, root.Layout.Width);
            Assert.AreEqual(200, root.Layout.Height);

            Assert.AreEqual(148, root_child0.Layout.Left);
            Assert.AreEqual(0, root_child0.Layout.Top);
            Assert.AreEqual(52, root_child0.Layout.Width);
            Assert.AreEqual(120, root_child0.Layout.Height);

            Assert.AreEqual(0, root_child1.Layout.Left);
            Assert.AreEqual(0, root_child1.Layout.Top);
            Assert.AreEqual(148, root_child1.Layout.Width);
            Assert.AreEqual(40, root_child1.Layout.Height);
        }

        [Test]
        public void percentage_flex_basis_cross_max_height()
        {
            YogaNode root_child0, root_child1;
            YogaNode root = Node(width: 200, height: 200)
                           .Add(root_child0 = Node(flexGrow: 1, flexBasis: 10.Percent(), maxHeight:60.Percent()))
                           .Add(root_child1 = Node(flexGrow: 4, flexBasis: 10.Percent(), maxHeight:20.Percent()));

            YogaArrange.CalculateLayout(root, YogaValue.YGUndefined, YogaValue.YGUndefined, Direction.LTR);

            Assert.AreEqual(0, root.Layout.Left);
            Assert.AreEqual(0, root.Layout.Top);
            Assert.AreEqual(200, root.Layout.Width);
            Assert.AreEqual(200, root.Layout.Height);

            Assert.AreEqual(0, root_child0.Layout.Left);
            Assert.AreEqual(0, root_child0.Layout.Top);
            Assert.AreEqual(200, root_child0.Layout.Width);
            Assert.AreEqual(120, root_child0.Layout.Height);

            Assert.AreEqual(0, root_child1.Layout.Left);
            Assert.AreEqual(120, root_child1.Layout.Top);
            Assert.AreEqual(200, root_child1.Layout.Width);
            Assert.AreEqual(40, root_child1.Layout.Height);

            YogaArrange.CalculateLayout(root, YogaValue.YGUndefined, YogaValue.YGUndefined, Direction.RTL);

            Assert.AreEqual(0, root.Layout.Left);
            Assert.AreEqual(0, root.Layout.Top);
            Assert.AreEqual(200, root.Layout.Width);
            Assert.AreEqual(200, root.Layout.Height);

            Assert.AreEqual(0, root_child0.Layout.Left);
            Assert.AreEqual(0, root_child0.Layout.Top);
            Assert.AreEqual(200, root_child0.Layout.Width);
            Assert.AreEqual(120, root_child0.Layout.Height);

            Assert.AreEqual(0, root_child1.Layout.Left);
            Assert.AreEqual(120, root_child1.Layout.Top);
            Assert.AreEqual(200, root_child1.Layout.Width);
            Assert.AreEqual(40, root_child1.Layout.Height);
        }

        [Test]
        public void percentage_flex_basis_main_max_width()
        {
            YogaConfig config = new YogaConfig();

            YogaNode root_child0, root_child1;
            YogaNode root = Node(flexDirection:FlexDirection.Row, width: 200, height: 200)
                           .Add(root_child0 = Node(flexGrow: 1, flexBasis: 15.Percent(), maxWidth:60.Percent()))
                           .Add(root_child1 = Node(flexGrow: 4, flexBasis: 10.Percent(), maxWidth:20.Percent()));

            YogaArrange.CalculateLayout(root, YogaValue.YGUndefined, YogaValue.YGUndefined, Direction.LTR);

            Assert.AreEqual(0, root.Layout.Left);
            Assert.AreEqual(0, root.Layout.Top);
            Assert.AreEqual(200, root.Layout.Width);
            Assert.AreEqual(200, root.Layout.Height);

            Assert.AreEqual(0, root_child0.Layout.Left);
            Assert.AreEqual(0, root_child0.Layout.Top);
            Assert.AreEqual(120, root_child0.Layout.Width);
            Assert.AreEqual(200, root_child0.Layout.Height);

            Assert.AreEqual(120, root_child1.Layout.Left);
            Assert.AreEqual(0, root_child1.Layout.Top);
            Assert.AreEqual(40, root_child1.Layout.Width);
            Assert.AreEqual(200, root_child1.Layout.Height);

            YogaArrange.CalculateLayout(root, YogaValue.YGUndefined, YogaValue.YGUndefined, Direction.RTL);

            Assert.AreEqual(0, root.Layout.Left);
            Assert.AreEqual(0, root.Layout.Top);
            Assert.AreEqual(200, root.Layout.Width);
            Assert.AreEqual(200, root.Layout.Height);

            Assert.AreEqual(80, root_child0.Layout.Left);
            Assert.AreEqual(0, root_child0.Layout.Top);
            Assert.AreEqual(120, root_child0.Layout.Width);
            Assert.AreEqual(200, root_child0.Layout.Height);

            Assert.AreEqual(40, root_child1.Layout.Left);
            Assert.AreEqual(0, root_child1.Layout.Top);
            Assert.AreEqual(40, root_child1.Layout.Width);
            Assert.AreEqual(200, root_child1.Layout.Height);
        }

        [Test]
        public void percentage_flex_basis_cross_max_width()
        {
            YogaConfig config = new YogaConfig();

            YogaNode root_child0, root_child1;
            YogaNode root = Node(width: 200, height: 200)
                           .Add(root_child0 = Node(flexGrow: 1, flexBasis: 10.Percent(), maxWidth:60.Percent()))
                           .Add(root_child1 = Node(flexGrow: 4, flexBasis: 15.Percent(), maxWidth:20.Percent()));

            YogaArrange.CalculateLayout(root, YogaValue.YGUndefined, YogaValue.YGUndefined, Direction.LTR);

            Assert.AreEqual(0, root.Layout.Left);
            Assert.AreEqual(0, root.Layout.Top);
            Assert.AreEqual(200, root.Layout.Width);
            Assert.AreEqual(200, root.Layout.Height);

            Assert.AreEqual(0, root_child0.Layout.Left);
            Assert.AreEqual(0, root_child0.Layout.Top);
            Assert.AreEqual(120, root_child0.Layout.Width);
            Assert.AreEqual(50, root_child0.Layout.Height);

            Assert.AreEqual(0, root_child1.Layout.Left);
            Assert.AreEqual(50, root_child1.Layout.Top);
            Assert.AreEqual(40, root_child1.Layout.Width);
            Assert.AreEqual(150, root_child1.Layout.Height);

            YogaArrange.CalculateLayout(root, YogaValue.YGUndefined, YogaValue.YGUndefined, Direction.RTL);

            Assert.AreEqual(0, root.Layout.Left);
            Assert.AreEqual(0, root.Layout.Top);
            Assert.AreEqual(200, root.Layout.Width);
            Assert.AreEqual(200, root.Layout.Height);

            Assert.AreEqual(80, root_child0.Layout.Left);
            Assert.AreEqual(0, root_child0.Layout.Top);
            Assert.AreEqual(120, root_child0.Layout.Width);
            Assert.AreEqual(50, root_child0.Layout.Height);

            Assert.AreEqual(160, root_child1.Layout.Left);
            Assert.AreEqual(50, root_child1.Layout.Top);
            Assert.AreEqual(40, root_child1.Layout.Width);
            Assert.AreEqual(150, root_child1.Layout.Height);
        }

        [Test]
        public void percentage_flex_basis_main_min_width()
        {
            YogaConfig config = new YogaConfig();

            YogaNode root_child0, root_child1;
            YogaNode root = Node(flexDirection:FlexDirection.Row, width: 200, height: 200)
                           .Add(root_child0 = Node(flexGrow: 1, flexBasis: 15.Percent(), minWidth:60.Percent()))
                           .Add(root_child1 = Node(flexGrow: 4, flexBasis: 10.Percent(), minWidth:20.Percent()));

            YogaArrange.CalculateLayout(root, YogaValue.YGUndefined, YogaValue.YGUndefined, Direction.LTR);

            Assert.AreEqual(0, root.Layout.Left);
            Assert.AreEqual(0, root.Layout.Top);
            Assert.AreEqual(200, root.Layout.Width);
            Assert.AreEqual(200, root.Layout.Height);

            Assert.AreEqual(0, root_child0.Layout.Left);
            Assert.AreEqual(0, root_child0.Layout.Top);
            Assert.AreEqual(120, root_child0.Layout.Width);
            Assert.AreEqual(200, root_child0.Layout.Height);

            Assert.AreEqual(120, root_child1.Layout.Left);
            Assert.AreEqual(0, root_child1.Layout.Top);
            Assert.AreEqual(80, root_child1.Layout.Width);
            Assert.AreEqual(200, root_child1.Layout.Height);

            YogaArrange.CalculateLayout(root, YogaValue.YGUndefined, YogaValue.YGUndefined, Direction.RTL);

            Assert.AreEqual(0, root.Layout.Left);
            Assert.AreEqual(0, root.Layout.Top);
            Assert.AreEqual(200, root.Layout.Width);
            Assert.AreEqual(200, root.Layout.Height);

            Assert.AreEqual(80, root_child0.Layout.Left);
            Assert.AreEqual(0, root_child0.Layout.Top);
            Assert.AreEqual(120, root_child0.Layout.Width);
            Assert.AreEqual(200, root_child0.Layout.Height);

            Assert.AreEqual(0, root_child1.Layout.Left);
            Assert.AreEqual(0, root_child1.Layout.Top);
            Assert.AreEqual(80, root_child1.Layout.Width);
            Assert.AreEqual(200, root_child1.Layout.Height);
        }

        [Test]
        public void percentage_flex_basis_cross_min_width()
        {
            YogaConfig config = new YogaConfig();

            YogaNode root_child0, root_child1;
            YogaNode root = Node(width: 200, height: 200)
                           .Add(root_child0 = Node(flexGrow: 1, flexBasis: 10.Percent(), minWidth:60.Percent()))
                           .Add(root_child1 = Node(flexGrow: 4, flexBasis: 15.Percent(), minWidth:20.Percent()));

            YogaArrange.CalculateLayout(root, YogaValue.YGUndefined, YogaValue.YGUndefined, Direction.LTR);

            Assert.AreEqual(0, root.Layout.Left);
            Assert.AreEqual(0, root.Layout.Top);
            Assert.AreEqual(200, root.Layout.Width);
            Assert.AreEqual(200, root.Layout.Height);

            Assert.AreEqual(0, root_child0.Layout.Left);
            Assert.AreEqual(0, root_child0.Layout.Top);
            Assert.AreEqual(200, root_child0.Layout.Width);
            Assert.AreEqual(50, root_child0.Layout.Height);

            Assert.AreEqual(0, root_child1.Layout.Left);
            Assert.AreEqual(50, root_child1.Layout.Top);
            Assert.AreEqual(200, root_child1.Layout.Width);
            Assert.AreEqual(150, root_child1.Layout.Height);

            YogaArrange.CalculateLayout(root, YogaValue.YGUndefined, YogaValue.YGUndefined, Direction.RTL);

            Assert.AreEqual(0, root.Layout.Left);
            Assert.AreEqual(0, root.Layout.Top);
            Assert.AreEqual(200, root.Layout.Width);
            Assert.AreEqual(200, root.Layout.Height);

            Assert.AreEqual(0, root_child0.Layout.Left);
            Assert.AreEqual(0, root_child0.Layout.Top);
            Assert.AreEqual(200, root_child0.Layout.Width);
            Assert.AreEqual(50, root_child0.Layout.Height);

            Assert.AreEqual(0, root_child1.Layout.Left);
            Assert.AreEqual(50, root_child1.Layout.Top);
            Assert.AreEqual(200, root_child1.Layout.Width);
            Assert.AreEqual(150, root_child1.Layout.Height);
        }

        [Test]
        public void percentage_multiple_nested_with_padding_margin_and_percentage_values()
        {
            YogaConfig config = new YogaConfig();

            YogaNode root_child0, root_child1, root_child0_child0, root_child0_child0_child0;
            YogaNode root = Node(width: 200, height: 200)
                           .Add(root_child0 = Node(flexGrow: 1, flexBasis: 10.Percent(), margin:new Edges(5), padding:new Edges(3), minWidth:60.Percent())
                               .Add(root_child0_child0 = Node(margin:new Edges(5), padding:new Edges(3.Percent()), width:50.Percent())
                                   .Add(root_child0_child0_child0 = Node(margin:new Edges(5.Percent()), padding:new Edges(3), width:45.Percent()))))
                           .Add(root_child1 = Node(flexGrow: 4, flexBasis: 15.Percent(), minWidth:20.Percent()));

            YogaArrange.CalculateLayout(root, YogaValue.YGUndefined, YogaValue.YGUndefined, Direction.LTR);

            Assert.AreEqual(0, root.Layout.Left);
            Assert.AreEqual(0, root.Layout.Top);
            Assert.AreEqual(200, root.Layout.Width);
            Assert.AreEqual(200, root.Layout.Height);

            Assert.AreEqual(5, root_child0.Layout.Left);
            Assert.AreEqual(5, root_child0.Layout.Top);
            Assert.AreEqual(190, root_child0.Layout.Width);
            Assert.AreEqual(48, root_child0.Layout.Height);

            Assert.AreEqual(8, root_child0_child0.Layout.Left);
            Assert.AreEqual(8, root_child0_child0.Layout.Top);
            Assert.AreEqual(92, root_child0_child0.Layout.Width);
            Assert.AreEqual(25, root_child0_child0.Layout.Height);

            Assert.AreEqual(10, root_child0_child0_child0.Layout.Left);
            Assert.AreEqual(10, root_child0_child0_child0.Layout.Top);
            Assert.AreEqual(36, root_child0_child0_child0.Layout.Width);
            Assert.AreEqual(6, root_child0_child0_child0.Layout.Height);

            Assert.AreEqual(0, root_child1.Layout.Left);
            Assert.AreEqual(58, root_child1.Layout.Top);
            Assert.AreEqual(200, root_child1.Layout.Width);
            Assert.AreEqual(142, root_child1.Layout.Height);

            YogaArrange.CalculateLayout(root, YogaValue.YGUndefined, YogaValue.YGUndefined, Direction.RTL);

            Assert.AreEqual(0, root.Layout.Left);
            Assert.AreEqual(0, root.Layout.Top);
            Assert.AreEqual(200, root.Layout.Width);
            Assert.AreEqual(200, root.Layout.Height);

            Assert.AreEqual(5, root_child0.Layout.Left);
            Assert.AreEqual(5, root_child0.Layout.Top);
            Assert.AreEqual(190, root_child0.Layout.Width);
            Assert.AreEqual(48, root_child0.Layout.Height);

            Assert.AreEqual(90, root_child0_child0.Layout.Left);
            Assert.AreEqual(8, root_child0_child0.Layout.Top);
            Assert.AreEqual(92, root_child0_child0.Layout.Width);
            Assert.AreEqual(25, root_child0_child0.Layout.Height);

            Assert.AreEqual(46, root_child0_child0_child0.Layout.Left);
            Assert.AreEqual(10, root_child0_child0_child0.Layout.Top);
            Assert.AreEqual(36, root_child0_child0_child0.Layout.Width);
            Assert.AreEqual(6, root_child0_child0_child0.Layout.Height);

            Assert.AreEqual(0, root_child1.Layout.Left);
            Assert.AreEqual(58, root_child1.Layout.Top);
            Assert.AreEqual(200, root_child1.Layout.Width);
            Assert.AreEqual(142, root_child1.Layout.Height);
        }

        [Test]
        public void percentage_margin_should_calculate_based_only_on_width()
        {
            YogaConfig config = new YogaConfig();

            YogaNode root_child0, root_child0_child0;
            YogaNode root = Node(width: 200, height: 100)
               .Add(root_child0 = Node(flexGrow: 1, margin: new Edges(10.Percent()))
                       .Add(root_child0_child0 = Node(width: 10, height: 10)));

            YogaArrange.CalculateLayout(root, YogaValue.YGUndefined, YogaValue.YGUndefined, Direction.LTR);

            Assert.AreEqual(0, root.Layout.Left);
            Assert.AreEqual(0, root.Layout.Top);
            Assert.AreEqual(200, root.Layout.Width);
            Assert.AreEqual(100, root.Layout.Height);

            Assert.AreEqual(20, root_child0.Layout.Left);
            Assert.AreEqual(20, root_child0.Layout.Top);
            Assert.AreEqual(160, root_child0.Layout.Width);
            Assert.AreEqual(60, root_child0.Layout.Height);

            Assert.AreEqual(0, root_child0_child0.Layout.Left);
            Assert.AreEqual(0, root_child0_child0.Layout.Top);
            Assert.AreEqual(10, root_child0_child0.Layout.Width);
            Assert.AreEqual(10, root_child0_child0.Layout.Height);

            YogaArrange.CalculateLayout(root, YogaValue.YGUndefined, YogaValue.YGUndefined, Direction.RTL);

            Assert.AreEqual(0, root.Layout.Left);
            Assert.AreEqual(0, root.Layout.Top);
            Assert.AreEqual(200, root.Layout.Width);
            Assert.AreEqual(100, root.Layout.Height);

            Assert.AreEqual(20, root_child0.Layout.Left);
            Assert.AreEqual(20, root_child0.Layout.Top);
            Assert.AreEqual(160, root_child0.Layout.Width);
            Assert.AreEqual(60, root_child0.Layout.Height);

            Assert.AreEqual(150, root_child0_child0.Layout.Left);
            Assert.AreEqual(0, root_child0_child0.Layout.Top);
            Assert.AreEqual(10, root_child0_child0.Layout.Width);
            Assert.AreEqual(10, root_child0_child0.Layout.Height);
        }

        [Test]
        public void percentage_padding_should_calculate_based_only_on_width()
        {
            YogaConfig config = new YogaConfig();

            YogaNode root_child0, root_child0_child0;
            YogaNode root = Node(width: 200, height: 100)
               .Add(root_child0 = Node(flexGrow: 1, padding: new Edges(10.Percent()))
                       .Add(root_child0_child0 = Node(width: 10, height: 10)));

            YogaArrange.CalculateLayout(root, YogaValue.YGUndefined, YogaValue.YGUndefined, Direction.LTR);

            Assert.AreEqual(0, root.Layout.Left);
            Assert.AreEqual(0, root.Layout.Top);
            Assert.AreEqual(200, root.Layout.Width);
            Assert.AreEqual(100, root.Layout.Height);

            Assert.AreEqual(0, root_child0.Layout.Left);
            Assert.AreEqual(0, root_child0.Layout.Top);
            Assert.AreEqual(200, root_child0.Layout.Width);
            Assert.AreEqual(100, root_child0.Layout.Height);

            Assert.AreEqual(20, root_child0_child0.Layout.Left);
            Assert.AreEqual(20, root_child0_child0.Layout.Top);
            Assert.AreEqual(10, root_child0_child0.Layout.Width);
            Assert.AreEqual(10, root_child0_child0.Layout.Height);

            YogaArrange.CalculateLayout(root, YogaValue.YGUndefined, YogaValue.YGUndefined, Direction.RTL);

            Assert.AreEqual(0, root.Layout.Left);
            Assert.AreEqual(0, root.Layout.Top);
            Assert.AreEqual(200, root.Layout.Width);
            Assert.AreEqual(100, root.Layout.Height);

            Assert.AreEqual(0, root_child0.Layout.Left);
            Assert.AreEqual(0, root_child0.Layout.Top);
            Assert.AreEqual(200, root_child0.Layout.Width);
            Assert.AreEqual(100, root_child0.Layout.Height);

            Assert.AreEqual(170, root_child0_child0.Layout.Left);
            Assert.AreEqual(20, root_child0_child0.Layout.Top);
            Assert.AreEqual(10, root_child0_child0.Layout.Width);
            Assert.AreEqual(10, root_child0_child0.Layout.Height);
        }

        [Test]
        public void percentage_absolute_position()
        {
            YogaConfig config = new YogaConfig();

            YogaNode root_child0;
            YogaNode root = Node(width: 200, height: 100)
               .Add(root_child0 = Node(positionType:PositionType.Absolute, left:30.Percent(), top: 10.Percent(), width:10, height:10));

            YogaArrange.CalculateLayout(root, YogaValue.YGUndefined, YogaValue.YGUndefined, Direction.LTR);

            Assert.AreEqual(0, root.Layout.Left);
            Assert.AreEqual(0, root.Layout.Top);
            Assert.AreEqual(200, root.Layout.Width);
            Assert.AreEqual(100, root.Layout.Height);

            Assert.AreEqual(60, root_child0.Layout.Left);
            Assert.AreEqual(10, root_child0.Layout.Top);
            Assert.AreEqual(10, root_child0.Layout.Width);
            Assert.AreEqual(10, root_child0.Layout.Height);

            YogaArrange.CalculateLayout(root, YogaValue.YGUndefined, YogaValue.YGUndefined, Direction.RTL);

            Assert.AreEqual(0, root.Layout.Left);
            Assert.AreEqual(0, root.Layout.Top);
            Assert.AreEqual(200, root.Layout.Width);
            Assert.AreEqual(100, root.Layout.Height);

            Assert.AreEqual(60, root_child0.Layout.Left);
            Assert.AreEqual(10, root_child0.Layout.Top);
            Assert.AreEqual(10, root_child0.Layout.Width);
            Assert.AreEqual(10, root_child0.Layout.Height);
        }

        [Test]
        public void percentage_width_height_undefined_parent_size()
        {
            YogaNode root_child0;
            YogaNode root = Node()
               .Add(root_child0 = Node(width: 50.Percent(), height: 50.Percent()));
                       
            YogaArrange.CalculateLayout(root, YogaValue.YGUndefined, YogaValue.YGUndefined, Direction.LTR);

            Assert.AreEqual(0, root.Layout.Left);
            Assert.AreEqual(0, root.Layout.Top);
            Assert.AreEqual(0, root.Layout.Width);
            Assert.AreEqual(0, root.Layout.Height);

            Assert.AreEqual(0, root_child0.Layout.Left);
            Assert.AreEqual(0, root_child0.Layout.Top);
            Assert.AreEqual(0, root_child0.Layout.Width);
            Assert.AreEqual(0, root_child0.Layout.Height);

            YogaArrange.CalculateLayout(root, YogaValue.YGUndefined, YogaValue.YGUndefined, Direction.RTL);

            Assert.AreEqual(0, root.Layout.Left);
            Assert.AreEqual(0, root.Layout.Top);
            Assert.AreEqual(0, root.Layout.Width);
            Assert.AreEqual(0, root.Layout.Height);

            Assert.AreEqual(0, root_child0.Layout.Left);
            Assert.AreEqual(0, root_child0.Layout.Top);
            Assert.AreEqual(0, root_child0.Layout.Width);
            Assert.AreEqual(0, root_child0.Layout.Height);
        }

        [Test]
        public void percent_within_flex_grow()
        {
            YogaConfig config = new YogaConfig();

            YogaNode root_child0, root_child1, root_child2, root_child1_child0;
            YogaNode root = Node(flexDirection: FlexDirection.Row, width: 350, height: 100)
               .Add(root_child0 = Node(width: 100))
               .Add(root_child1 = Node(flexGrow: 1)
                     .Add(root_child1_child0 = Node(width: 100.Percent())))
               .Add(root_child2 = Node(width:100));

            YogaArrange.CalculateLayout(root, YogaValue.YGUndefined, YogaValue.YGUndefined, Direction.LTR);

            Assert.AreEqual(0, root.Layout.Left);
            Assert.AreEqual(0, root.Layout.Top);
            Assert.AreEqual(350, root.Layout.Width);
            Assert.AreEqual(100, root.Layout.Height);

            Assert.AreEqual(0, root_child0.Layout.Left);
            Assert.AreEqual(0, root_child0.Layout.Top);
            Assert.AreEqual(100, root_child0.Layout.Width);
            Assert.AreEqual(100, root_child0.Layout.Height);

            Assert.AreEqual(100, root_child1.Layout.Left);
            Assert.AreEqual(0, root_child1.Layout.Top);
            Assert.AreEqual(150, root_child1.Layout.Width);
            Assert.AreEqual(100, root_child1.Layout.Height);

            Assert.AreEqual(0, root_child1_child0.Layout.Left);
            Assert.AreEqual(0, root_child1_child0.Layout.Top);
            Assert.AreEqual(150, root_child1_child0.Layout.Width);
            Assert.AreEqual(0, root_child1_child0.Layout.Height);

            Assert.AreEqual(250, root_child2.Layout.Left);
            Assert.AreEqual(0, root_child2.Layout.Top);
            Assert.AreEqual(100, root_child2.Layout.Width);
            Assert.AreEqual(100, root_child2.Layout.Height);

            YogaArrange.CalculateLayout(root, YogaValue.YGUndefined, YogaValue.YGUndefined, Direction.RTL);

            Assert.AreEqual(0, root.Layout.Left);
            Assert.AreEqual(0, root.Layout.Top);
            Assert.AreEqual(350, root.Layout.Width);
            Assert.AreEqual(100, root.Layout.Height);

            Assert.AreEqual(250, root_child0.Layout.Left);
            Assert.AreEqual(0, root_child0.Layout.Top);
            Assert.AreEqual(100, root_child0.Layout.Width);
            Assert.AreEqual(100, root_child0.Layout.Height);

            Assert.AreEqual(100, root_child1.Layout.Left);
            Assert.AreEqual(0, root_child1.Layout.Top);
            Assert.AreEqual(150, root_child1.Layout.Width);
            Assert.AreEqual(100, root_child1.Layout.Height);

            Assert.AreEqual(0, root_child1_child0.Layout.Left);
            Assert.AreEqual(0, root_child1_child0.Layout.Top);
            Assert.AreEqual(150, root_child1_child0.Layout.Width);
            Assert.AreEqual(0, root_child1_child0.Layout.Height);

            Assert.AreEqual(0, root_child2.Layout.Left);
            Assert.AreEqual(0, root_child2.Layout.Top);
            Assert.AreEqual(100, root_child2.Layout.Width);
            Assert.AreEqual(100, root_child2.Layout.Height);
        }

        [Test]
        public void percentage_container_in_wrapping_container()
        {
            YogaConfig config = new YogaConfig();

            YogaNode root_child0, root_child0_child0, root_child0_child0_child0, root_child0_child0_child1;
            YogaNode root = Node(justifyContent: Justify.Center, alignItems: YogaAlign.Center, width: 200, height: 200)
               .Add(
                    root_child0 = Node()
                       .Add(
                            root_child0_child0 = Node(flexDirection: FlexDirection.Row, justifyContent: Justify.Center, width: 100.Percent())
                                                .Add(root_child0_child0_child0 = Node(width: 50, height: 50))
                                                .Add(root_child0_child0_child1 = Node(width: 50, height: 50))
                        )
                );
                           
            YogaArrange.CalculateLayout(root, YogaValue.YGUndefined, YogaValue.YGUndefined, Direction.LTR);

            Assert.AreEqual(0, root.Layout.Left);
            Assert.AreEqual(0, root.Layout.Top);
            Assert.AreEqual(200, root.Layout.Width);
            Assert.AreEqual(200, root.Layout.Height);

            Assert.AreEqual(50, root_child0.Layout.Left);
            Assert.AreEqual(75, root_child0.Layout.Top);
            Assert.AreEqual(100, root_child0.Layout.Width);
            Assert.AreEqual(50, root_child0.Layout.Height);

            Assert.AreEqual(0, root_child0_child0.Layout.Left);
            Assert.AreEqual(0, root_child0_child0.Layout.Top);
            Assert.AreEqual(100, root_child0_child0.Layout.Width);
            Assert.AreEqual(50, root_child0_child0.Layout.Height);

            Assert.AreEqual(0, root_child0_child0_child0.Layout.Left);
            Assert.AreEqual(0, root_child0_child0_child0.Layout.Top);
            Assert.AreEqual(50, root_child0_child0_child0.Layout.Width);
            Assert.AreEqual(50, root_child0_child0_child0.Layout.Height);

            Assert.AreEqual(50, root_child0_child0_child1.Layout.Left);
            Assert.AreEqual(0, root_child0_child0_child1.Layout.Top);
            Assert.AreEqual(50, root_child0_child0_child1.Layout.Width);
            Assert.AreEqual(50, root_child0_child0_child1.Layout.Height);

            YogaArrange.CalculateLayout(root, YogaValue.YGUndefined, YogaValue.YGUndefined, Direction.RTL);

            Assert.AreEqual(0, root.Layout.Left);
            Assert.AreEqual(0, root.Layout.Top);
            Assert.AreEqual(200, root.Layout.Width);
            Assert.AreEqual(200, root.Layout.Height);

            Assert.AreEqual(50, root_child0.Layout.Left);
            Assert.AreEqual(75, root_child0.Layout.Top);
            Assert.AreEqual(100, root_child0.Layout.Width);
            Assert.AreEqual(50, root_child0.Layout.Height);

            Assert.AreEqual(0, root_child0_child0.Layout.Left);
            Assert.AreEqual(0, root_child0_child0.Layout.Top);
            Assert.AreEqual(100, root_child0_child0.Layout.Width);
            Assert.AreEqual(50, root_child0_child0.Layout.Height);

            Assert.AreEqual(50, root_child0_child0_child0.Layout.Left);
            Assert.AreEqual(0, root_child0_child0_child0.Layout.Top);
            Assert.AreEqual(50, root_child0_child0_child0.Layout.Width);
            Assert.AreEqual(50, root_child0_child0_child0.Layout.Height);

            Assert.AreEqual(0, root_child0_child0_child1.Layout.Left);
            Assert.AreEqual(0, root_child0_child0_child1.Layout.Top);
            Assert.AreEqual(50, root_child0_child0_child1.Layout.Width);
            Assert.AreEqual(50, root_child0_child0_child1.Layout.Height);
        }

        [Test]
        public void percent_absolute_position()
        {
            YogaConfig config = new YogaConfig();

            YogaNode root_child0, root_child0_child0, root_child0_child1;
            YogaNode root = Node(width: 60, height: 50)
                   .Add(root_child0 = Node(flexDirection: FlexDirection.Row, positionType:PositionType.Absolute, left:50.Percent(), width:100.Percent(), height:50)
                         .Add(root_child0_child0 = Node(width:100.Percent()))
                         .Add(root_child0_child1 = Node(width:100.Percent())));

            YogaArrange.CalculateLayout(root, YogaValue.YGUndefined, YogaValue.YGUndefined, Direction.LTR);

            Assert.AreEqual(0, root.Layout.Left);
            Assert.AreEqual(0, root.Layout.Top);
            Assert.AreEqual(60, root.Layout.Width);
            Assert.AreEqual(50, root.Layout.Height);

            Assert.AreEqual(30, root_child0.Layout.Left);
            Assert.AreEqual(0, root_child0.Layout.Top);
            Assert.AreEqual(60, root_child0.Layout.Width);
            Assert.AreEqual(50, root_child0.Layout.Height);

            Assert.AreEqual(0, root_child0_child0.Layout.Left);
            Assert.AreEqual(0, root_child0_child0.Layout.Top);
            Assert.AreEqual(60, root_child0_child0.Layout.Width);
            Assert.AreEqual(50, root_child0_child0.Layout.Height);

            Assert.AreEqual(60, root_child0_child1.Layout.Left);
            Assert.AreEqual(0, root_child0_child1.Layout.Top);
            Assert.AreEqual(60, root_child0_child1.Layout.Width);
            Assert.AreEqual(50, root_child0_child1.Layout.Height);

            YogaArrange.CalculateLayout(root, YogaValue.YGUndefined, YogaValue.YGUndefined, Direction.RTL);

            Assert.AreEqual(0, root.Layout.Left);
            Assert.AreEqual(0, root.Layout.Top);
            Assert.AreEqual(60, root.Layout.Width);
            Assert.AreEqual(50, root.Layout.Height);

            Assert.AreEqual(30, root_child0.Layout.Left);
            Assert.AreEqual(0, root_child0.Layout.Top);
            Assert.AreEqual(60, root_child0.Layout.Width);
            Assert.AreEqual(50, root_child0.Layout.Height);

            Assert.AreEqual(0, root_child0_child0.Layout.Left);
            Assert.AreEqual(0, root_child0_child0.Layout.Top);
            Assert.AreEqual(60, root_child0_child0.Layout.Width);
            Assert.AreEqual(50, root_child0_child0.Layout.Height);

            Assert.AreEqual(-60, root_child0_child1.Layout.Left);
            Assert.AreEqual(0, root_child0_child1.Layout.Top);
            Assert.AreEqual(60, root_child0_child1.Layout.Width);
            Assert.AreEqual(50, root_child0_child1.Layout.Height);
        }
    }
}
